### ISSUE TITLE
11.3 & 11.4: define the mitigation

### ISSUE THREAD

**Issue by samuelweiler** [w3c/secure-payment-confirmation#143] opened 2021-10-07 01:58 UTC
Can we standardize this mitigation, and is this mitigation sufficient?  So rather than "One possible way to defeat this ..." just provide instructions?  As in https://github.com/w3c/secure-payment-confirmation/issues/142, the instructions might better fit elsewhere in the doc.

**Comment by cyberphone** [comment] 2021-11-02 16:15
If you instead of deprecating https://w3c.github.io/payment-method-basic-card/ added a `credentialId` attribute to each card entry and as a final step encrypted the authorization data, W3C would have the industry's most privacy conserving user payment authorization solution, and with a UX that would be second to none!

Since basic-cards is still available in Chrome, the card (payment instrument) database is already in place. `PaymentRequest` would then finally get the important role it was once designed for.  Merchant integration code (with respect to user payment authorization), would be a mere 30-40 lines of JavaScript since no complex and privacy-impeding external communication would be needed for locating and fetching `credentialid`, logotypes, or account data.  That is, all user data required is already featured in the locally registered payment instruments.

With yet a minute addition to card entries, the scheme could support any account based payment system which also would be an industry first.

**Comment by stephenmcgruer** [comment] 2021-11-04 18:14
(Without wanting to re-litigate discussions that have happened over and over, nor get too off-topic in this issue.)

As far as I can tell, the proposed solution by @cyberphone requires no new browser technology. Whilst it is described above on top of basic-card, is there a **technical** reason that a digital wallet provider that is not the browser could not build such a system?

**Comment by cyberphone** [comment] 2021-11-04 21:05
As a builder of native Android apps I can attest that you are essentially only limited by your imagination.  However, creating globally accepted standards is another story.  As we have already seen with the market-wise rejected PaymentHandler, you apparently need a very competitive solution in order to stand a slim chance getting industry traction, even if it runs in Chrome.  There were never any open discussions, there were only my monologs which of course is totally uninteresting.  Even for me 😟 The predecessors to [RFC 8785](https://www.rfc-editor.org/rfc/rfc8785.html) were publicly slammed more than once which of course was quite depressing but I also learnt a lot along the way which made the final solution much better so in retrospect I'm actually thankful 😀 Anyway, what I'm advocating has approximately the same need for new browser technology as SPC.

**Comment by stephenmcgruer** [comment] 2022-03-02 15:28
(Note: this is now 11.3 & 11.4)

**Comment by ianbjacobs** [comment] 2022-05-04 18:49
@samuelweiler, there was agreement at today's call that this is a dup of #77 and we can close it in favor of 77. Do you want to remove the privacy-needs-resolution label?

**Comment by samuelweiler** [comment] 2022-05-04 19:01
I thought I did that earlier.  grumble grumble labels grumble.

**Comment by ianbjacobs** [comment] 2022-05-04 20:04
Closed as a duplicate of #77.

**Closed by ianbjacobs** 2022-05-04 20:04 UTC
Labels: privacy-tracker
